// src/routes/+page.svelte
<div class="min-h-screen flex flex-col items-center justify-center select-none">
  <p class="font-mono">
    <span class="opacity-80">welcome to</span>
    <span class="text-accent font-semibold">
      <span contenteditable="true">ethen</span>.app
    </span><span>{"™"}</span>
  </p>
  <a
    href="/creators"
    class="unstyled-link opacity-50 hover:underline hover:decoration-accent/80"
  >
    because the internet wasn't boring enough
  </a>
</div>

// src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/")({ component: Home });

function Home() {
  return (
    <div className="p-8 flex flex-col items-center justify-center min-h-dvh">
      <h1 className="text-3xl font-semibold">welcome to ethen.app</h1>
      <p className="mt-2">
        Ethen's corner of the web. <Route.Link to="/projects">projects (WIP)</Route.Link>
      </p>
    </div>
  );
}
